blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles

  root 'welcome#index'
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
    validates :title,
        presence: true, 
        length: { minimum: 5 } 
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article = Article.find(params[:id])

        @article.destroy
        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any? %>
        <div id="errors">
            <h2>
                <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
            </h2>
            <ul>
                <% @article.errors.full_messages.each do |e| %>
                    <li><%= e %></li>
                <% end %> 
            </ul>
        </div>
    <% end %>

    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :text %><br>
        <%= f.text_field :text %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Home', articles_path %>

blog/app/views/articles/index.html.erb
<h1>All Articles</h1>
<% if @articles.count > 0 %>
    <% @articles.each do |a| %>
        <h2><%= a.title %></h2>
        <p><%= a.text %></p>
        <%= link_to "Show", article_path(a) %>
        <%= link_to "Edit", edit_article_path(a) %>
        <%= link_to "Delete", article_path(a),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
    <% end %>
<% else %>
    <h2>No Articles</h2>
<% end %>
<p>
    <%= link_to "New Article", new_article_path %>
</p>

blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Home', articles_path %>

blog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.text %></p>
<%= link_to "Delete",
    article_path(@article),
    method: :delete,
    data: { confirm: 'Are you sure?' }
%>
<%= link_to "Edit", edit_article_path(@article) %>
<%= link_to "Back", articles_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/welcome/index.html.erb
<h1>Hell0 W0rlD!</h1>
<%= link_to "My blog", controller: 'articles' %>