task_list/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :tasks

  root 'home#index'
end

task_list/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

task_list/app/models/task.rb
class Task < ApplicationRecord
end

task_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

task_list/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @tasks = Task.all
    end
end

task_list/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def show
        @task = Task.find(params[:id])
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)

        @task.save
        redirect_to @task
    end

    def destroy
        @task = Task.find(params[:id])

        @task.destroy
        redirect_to home_index_path
    end

    private
        def task_params
            params.require(:task).permit(:title, :description)
        end
end

task_list/app/helpers/application_helper.rb
module ApplicationHelper
end

task_list/app/helpers/home_helper.rb
module HomeHelper
end

task_list/app/helpers/tasks_helper.rb
module TasksHelper
end

task_list/app/views/home/index.html.erb
<h1>Task List</h1>
<% @tasks.each do |t| %>
    <h1><%= link_to t.title, task_path(t) %></h1>
    <!--<p><%= t.description %></p>-->
<% end %>
<%= link_to 'NEW', new_task_path %>

task_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

task_list/app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <br>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <br>
    <br>
    <%= f.submit %>
<% end %> 

task_list/app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.description %></p>
<%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Home', home_index_path %>